In [ ]:
#5

def strlen(str):
  return len(str)
  

In [ ]:
#6
def charfreq(str):
  chardict = dict()
  for char in str:
    if not char in chardict.keys():
      chardict(char) = 1
    else:
      chardict(char) += 1
  return chardict
charfreq("google.com")

In [ ]:
#8
a = ['hello', 'world', 'python', 'cat']
def wordcount(array):
  longest = max(array, key=len)
  print(longest)
  print(len(longest))
wordcount(a)

python
6


In [ ]:
#9
num = [1,2,3,4,5,6]
def sum(array):
  a = 0
  for number in array:
    a = a + number
  print(a)
sum(num)

21


In [ ]:
#10
num = [1,2,3,4,5,6]
def times(array):
  a = 1
  for number in array:
    a = a * number
  print(a)
times(num)

720


In [ ]:
#11
num = [1,2,3,4,5,6]
def maximum(array):
  maxi = num[0]
  for number in array:
    if number > maxi:
      maxi = number
  print(maxi)
maximum(num)

6


In [ ]:
#12
num = [1,2,3,4,5,6]
def minimum(array):
  mini = num[0]
  for number in array:
    if number < mini:
      mini = number
  print(mini)
minimum(num)

1


In [ ]:
#13
list = ['aabc', 'xyz', 'aba', '1221']
def same(array):
  a = 0
  for word in array:
    if len(word) >= 2:
      if word[0] == word[-1]:
        a = a + 1
  print(a)
same(list)

2


In [ ]:
#14
def removeDup(1):
  return list(set(1))
removeDup([1,1,1,2,3,4])

In [ ]:
#16
list = ['aabc', 'xyz', 'aba', '1221', 'aba']
def empty(array):
  for word in array:
    if len(word) == 0:
      array.remove(word)
  print(array)
empty(list)

['aabc', 'xyz', 'aba', '1221', 'aba']


In [ ]:
#practice 2
#1

In [ ]:
#3
a = ['a','s','d','f','g','h']
def remove(array):
  if len(a) >= 3:
    removed = array.pop(1)
    print(removed)
  if len(a) < 3:
    break
remove(a)

SyntaxError: ignored

In [ ]:
tuples = ('z','a','d','f','g','e','e','k')
def reverses(tuple):
  reversed(tuple)
  print(tuple)
reverses(tuples)

('z', 'a', 'd', 'f', 'g', 'e', 'e', 'k')


In [ ]:
def sum(array):
  a = 0
  for num in array:
    a = a + num
  print(a)
sum([1,2,3])


6


In [ ]:
def pro(array):
  a = 1
  for num in array:
    a = a * num
  print(a)
pro([1,2,3])

6


In [ ]:
def rev_list():
  return l(len(l)-l::-l)

print(rev_list([1,2,3]))

[3, 2, 1]


In [ ]:
import math
def fact(array):  
  a = 1
  if array==1 or array==0:
    return 1 
  else:
    a = array * (array - 1)
    print(a)

fact([1,2,3])

TypeError: ignored

In [ ]:
def sum(array):
  a = 0
  while 4 >= a:
    if a == 0:
      a = a + array[a]
      print(a)
    elif a == 1:
      a = a + array[a]
      print(a)
    elif a ==2:
      a = a + array[a]
      print(a)
    elif a == 3:
      a = a + array[a]
      print(a)
    elif a == 4:
      a = a + array[a]
      print(a)
sum([1,2,3,4])

1
3
7


In [ ]:
def pro(array):
  a = 0
  b = 1
  while 4 >= a:
    if a == 0:
      b = b * array[a]
      print(b)
      a = a + 1
    elif a == 1:
      b = b * array[a]
      print(b)
      a = a + 1
    elif a ==2:
      b = b * array[a]
      print(b)
      a = a + 1
    elif a == 3:
      b = b * array[a]
      print(b)
      a = a + 1
    elif a == 4:
      b = b * array[a]
      print(b)
      a = a + 1
sum([1,2,3,4])

1
3
7


In [ ]:
a = ['hello', 'world', 'python', 'cat']
def wordcount(array):
  longest = max(array, key=len)
  shortest = min(array, key=len)
  print(longest)
  print(len(longest))
  print(shortest)
  print(len(shortest))
wordcount(a)

python
6
cat
3


In [ ]:
def unique(l):
  x = []
  for a in l:
    if a not in x:
      x.append(a)
  return x

unique([1,1,2,2,2,2,3,4,5,6,6,6])

[1, 2, 3, 4, 5, 6]

In [ ]:
l =[1,2,3,4,'abc', [1,2]]
l.append(5)
l

[1, 2, 3, 4, 'abc', [1, 2], 5]

In [ ]:
t1 = (1,2,3,4)

In [ ]:
t1[1:]

(2, 'a', 'b')

In [ ]:
x = ['c', 'perl', 'java', 'ruby', 'python', 'haskell']
def lensort(l):
  l.sort(key = len)
  print(l)

lensort(x)

['c', 'perl', 'java', 'ruby', 'python', 'haskell']


In [ ]:
x = ["python", "java", "Python", "Java"]
def unique(l,key):
  return list(set([key(s) for s in l]))

unique(["python", "java", "Python", "Java"], key=lambda s: s.lower())

['python', 'java']

In [ ]:


x = [0, 1, 2, 3, 4]
y = []
def square(o):
  for num in x:
    y.append(num * num)
  print(y)

square(y)

[0, 1, 4, 9, 16]


In [ ]:
def is_even(num):
  return num % 2 == 0

x = [1,2,3,4,5,6]

y = []

for num in x:
  if is_even(num) == True:
    y.append(num)

is_even(y)

TypeError: ignored

In [ ]:
def triplets(n): 
    return [ (a,c-a,c) for c in range(2,n) for a in range(1,c//2+1) ]
triplets(5)

[(1, 1, 2), (1, 2, 3), (1, 3, 4), (2, 2, 4)]

In [ ]:
a = {'x': 1, 'y': 2, 'a': 3}
a.values()


dict_values([1, 2, 3])

In [ ]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
print("a : List =", a)
b = np.array(a)
print("b : np array =", b)

a : List = [1, 2, 3, 4, 5, 6, 7, 8]
b : np array = [1 2 3 4 5 6 7 8]


In [ ]:
# Create a length-10 integer array filled with zeros
a0 = np.zeros(10, dtype=int)
print(a0.shape)
print(a0)
# Create a 3x5 floating-point array filled with ones
a1 = np.ones((2, 5), dtype=float)
print(a1.shape)
print(a1)
# Create a 3x5 array filled with 3.14
af = np.full((2, 5), 3.14)
print(af)

(10,)
[0 0 0 0 0 0 0 0 0 0]
(2, 5)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print (np.concatenate([x, y]), '\n')
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1] 

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
x = np.arange(0,8).reshape((2, 4))
y = np.arange(8,16).reshape((2, 4))
print (x, '\n')
print (y, '\n')
print (np.concatenate([x,y], axis=0), '\n')
print (np.vstack([x,y]), '\n')
print (np.concatenate([x,y], axis=1), '\n')
print (np.hstack([x,y]))

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]] 

[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [ ]:
a = [12.23, 13.32, 100, 36.32]
b = np.array(a)
print("b : np array =", b)

b : np array = [ 12.23  13.32 100.    36.32]


In [ ]:
np.random.randint(1, 11, size=(3, 3))

array([[ 7,  5,  5],
       [ 8,  2,  4],
       [10,  4,  4]])

In [ ]:
a0 = np.zeros(11, dtype=int)
print(a0)

[0 0 0 0 0 0 0 0 0 0 0]


In [4]:
import numpy as np
x1 = np.arange(50)
print (x1[10:39])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38]


In [47]:
#7
def tofloat(arr):
  return np.array(arr, dtype=float)

print(tofloat([1,2,3,4]))


[1. 2. 3. 4.]


In [54]:
#8
a1 = np.ones((1,10))
a2 = np.array([1,0,0,0,0,0,0,0,0,1])
a = np.concatenate((a1)+(a2)*8+(a1), axis = 0)
print(a)

[10.  2.  2.  2.  2.  2.  2.  2.  2. 10.]


In [55]:
b1 = np.zeros((8,8))
b2 = np.ones((1,8))
b3 = np.ones((10,1))
b = np.concatenate([b2, b1, b2], axis=0)
b = np.concatenate([b3,b,b3], axis=1)
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [56]:
#10
def checkerboard(n):
  c = np.ones((n,n))
  for i in range(n):
    for j in range(n):
      if (i+j)%2 == 1:
        c[i,j] = 0
  return c

print(checkerboard(10))


[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [25]:
#11


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
dtype: int64
ndim:  2
shape: (3, 4)
size:  12
itemsize: 8 bytes
nbytes: 96 bytes
