In [1]:
import numpy as np

In [2]:
def checkerboard(n):
  c = np.ones((n,n))
  for i in range(n):
    for j in range(n):
      if (i+j)%2 == 1:
        c[i,j] = 0
  return c

print(checkerboard(10))

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [3]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print(np.intersect1d(array1, array2))

[10 40]


In [8]:
x = np.array([10, 10, 20, 20, 30, 30])
print(x)
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("\n",x)
print(np.unique(x))

[10 10 20 20 30 30]
[10 20 30]

 [[1 1]
 [2 3]]
[1 2 3]


In [11]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print(array1)
array2 = [10, 30, 40, 50, 70, 90]
print(array2)
print(np.setdiff1d(array1, array2))

[ 0 10 20 40 60 80]
[10, 30, 40, 50, 70, 90]
[ 0 20 60 80]


In [ ]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print(array1)
array2 = [10, 30, 40, 50, 70]
print(array2)
print(np.setxor1d(array1, array2))

In [13]:
a = [1, 2, 3, 4]
x = np.tile(a, 3)
print(x)


[1 2 3 4 1 2 3 4 1 2 3 4]


In [14]:
x = np.repeat(3, 4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


In [15]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
print(np.argmax(x))
print(np.argmin(x))

[1 2 3 4 5 6]
5
0
